# Generated by Django 3.2.25 on 2024-12-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
